# Generated by Django 2.0.5 on 2018-11-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=32)),
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('SEX_GBN', models.IntegerField(default=0)),
                ('AGE_GBN', models.IntegerField(default=0)),
                ('JOB_GBN', models.IntegerField(default=0)),
                ('ADD_GBN', models.IntegerField(default=0)),
                ('INCOME_GBN', models.IntegerField(default=0)),
                ('MARRY_Y', models.IntegerField(default=0)),
                ('DOUBLE_IN', models.IntegerField(default=0)),
                ('NUMCHILD', models.IntegerField(default=0)),
                ('TOT_ASSET', models.IntegerField(default=0)),
                ('ASS_FIN', models.IntegerField(default=0)),
                ('ASS_REAL', models.IntegerField(default=0)),
                ('ASS_ETC', models.IntegerField(default=0)),
                ('M_TOT_SAVING', models.IntegerField(default=0)),
                ('M_JEOK', models.IntegerField(default=0)),
                ('CHUNG_Y', models.IntegerField(default=0)),
                ('M_FUND_STOCK', models.IntegerField(default=0)),
                ('M_FUND', models.IntegerField(default=0)),
                ('M_STOCK', models.IntegerField(default=0)),
                ('M_SAVING_INSUR', models.IntegerField(default=0)),
                ('M_CHUNG', models.IntegerField(default=0)),
                ('TOT_DEBT', models.IntegerField(default=0)),
                ('D_SHINYONG', models.IntegerField(default=0)),
                ('D_DAMBO', models.IntegerField(default=0)),
                ('D_JUTEAKDAMBO', models.IntegerField(default=0)),
                ('D_JEONSEA', models.IntegerField(default=0)),
                ('RETIRE_NEED', models.IntegerField(default=0)),
                ('FOR_RETIRE', models.IntegerField(default=0)),
                ('TOT_YEA', models.IntegerField(default=0)),
                ('TOT_JEOK', models.IntegerField(default=0)),
                ('TOT_CHUNG', models.IntegerField(default=0)),
                ('TOT_FUND', models.IntegerField(default=0)),
                ('TOT_ELS_ETE', models.IntegerField(default=0)),
                ('TOT_SOBI', models.IntegerField(default=0)),
                ('M_CRD_SPD', models.IntegerField(default=0)),
                ('Check_field', models.IntegerField(default=0)),
                ('Product', models.IntegerField(default=0)),
            ],
        ),
    ]
